// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgRGtg1Mai_xM1VryEW4jFWuIM-7VTty0',
    appId: '1:269696520962:web:ee7bd6b5e054eb33f8681b',
    messagingSenderId: '269696520962',
    projectId: 'flutter-auth-app-ad598',
    authDomain: 'flutter-auth-app-ad598.firebaseapp.com',
    storageBucket: 'flutter-auth-app-ad598.firebasestorage.app',
    measurementId: 'G-92VGTG2143',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFtA3I0uNwUbD5dF3OSudHsU-TjlZO8AY',
    appId: '1:269696520962:android:8532bea8b5c04760f8681b',
    messagingSenderId: '269696520962',
    projectId: 'flutter-auth-app-ad598',
    storageBucket: 'flutter-auth-app-ad598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjGsG-8f5PKVokojBGO6s5W1seId2HNs',
    appId: '1:269696520962:ios:2221edec7ac00a2cf8681b',
    messagingSenderId: '269696520962',
    projectId: 'flutter-auth-app-ad598',
    storageBucket: 'flutter-auth-app-ad598.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQjGsG-8f5PKVokojBGO6s5W1seId2HNs',
    appId: '1:269696520962:ios:2221edec7ac00a2cf8681b',
    messagingSenderId: '269696520962',
    projectId: 'flutter-auth-app-ad598',
    storageBucket: 'flutter-auth-app-ad598.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgRGtg1Mai_xM1VryEW4jFWuIM-7VTty0',
    appId: '1:269696520962:web:ea5971b6d58cf228f8681b',
    messagingSenderId: '269696520962',
    projectId: 'flutter-auth-app-ad598',
    authDomain: 'flutter-auth-app-ad598.firebaseapp.com',
    storageBucket: 'flutter-auth-app-ad598.firebasestorage.app',
    measurementId: 'G-Q1LE0BBLFV',
  );
}
